/* prettier-ignore-start */

/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router
// Import Routes
import { Route as rootRoute } from "./routes/__root"
import { Route as IndexImport } from "./routes/index"
import { Route as ModManagerIndexImport } from "./routes/mod-manager/index"
import { Route as ServerBrowserIndexImport } from "./routes/server-browser/index"
import { Route as SettingsIndexImport } from "./routes/settings/index"

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const SettingsIndexRoute = SettingsIndexImport.update({
  path: "/settings/",
  getParentRoute: () => rootRoute,
} as any)

const ServerBrowserIndexRoute = ServerBrowserIndexImport.update({
  path: "/server-browser/",
  getParentRoute: () => rootRoute,
} as any)

const ModManagerIndexRoute = ModManagerIndexImport.update({
  path: "/mod-manager/",
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/mod-manager/": {
      preLoaderRoute: typeof ModManagerIndexImport
      parentRoute: typeof rootRoute
    }
    "/server-browser/": {
      preLoaderRoute: typeof ServerBrowserIndexImport
      parentRoute: typeof rootRoute
    }
    "/settings/": {
      preLoaderRoute: typeof SettingsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ModManagerIndexRoute,
  ServerBrowserIndexRoute,
  SettingsIndexRoute,
])

/* prettier-ignore-end */
